# Generated by Django 4.2.1 on 2023-07-27 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hometown',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='hometown',
            name='lname',
        ),
    ]
